cf-kibana/kibana-7.9.3-linux-x86_64.tar.gz:
  size: 295755102
  object_id: 74b514c5-0669-4b75-71f0-9b1f81240e97
  sha: sha256:20106e084f717270ce38290d1d3908db7de09b16233688ce0ec41e1d0dffddd6
redis/redis-3.2.9.tar.gz:
  size: 1547695
  object_id: d0b8b484-f735-428c-4bb7-5129d1ef45aa
  sha: sha256:6eaacfa983b287e440d0839ead20c2231749d5d6b78bbe0e0ffa3a890c59ff26
requests/certifi-2019.11.28-py2.py3-none-any.whl:
  size: 156030
  object_id: 26a907f0-c975-478e-46f2-fd178e510f3d
  sha: sha256:017c25db2a153ce562900032d5bc68e9f191e44e9a0f762f373977de9df1fbb3
requests/chardet-3.0.4-py2.py3-none-any.whl:
  size: 133356
  object_id: 51ef32df-8fa2-4460-5278-dac9c2125118
  sha: sha256:fc323ffcaeaed0e0a02bf4d117757b98aed530d9ed4531e3e15460124c106691
requests/idna-2.8-py2.py3-none-any.whl:
  size: 58594
  object_id: bbc5a76d-882a-4279-6c3a-722642885fd9
  sha: sha256:ea8b7f6188e6fa117537c3df7da9fc686d485087abf6ac197f9c46432f7e4a3c
requests/requests-2.22.0-py2.py3-none-any.whl:
  size: 57952
  object_id: 45e6e327-b6a7-462f-46ef-567cef18358f
  sha: sha256:9cf5292fcd0f598c671cfc1e0d7d1a7f13bb8085e9a590f48c010551dc6c4b31
requests/urllib3-1.25.8-py2.py3-none-any.whl:
  size: 125642
  object_id: c8ec5584-0428-4c10-5f42-df0392db3985
  sha: sha256:2f3db8b19923a873b3e5256dc9c2dedfa883e33d87c690d9c7913e1f40673cdc
ruby/rake-12.3.2.gem:
  size: 87040
  object_id: db165d94-7485-4db2-5fd3-305f9202f70c
  sha: sha256:56362f144a29ffbc5e49161a80ca4e2e6b7da2946170067d624d7603ed51c5eb
